The following tutorial has been adopted from [_**Quickstart tutorial**: Numpy User Guide_]
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

# NumPy Array
NumPy array is a homogeneous and multidimensional array. All of the elements are same type and indexed by a tuple of positive integers. 
NumPy’s array class is called ` ndarray `. The alias ` array ` refers to ` ndarray `. Note that ` numpy.array ` is not the same as the Standard Python Library class ` array.array `, which only handles one-dimensional arrays and offers less functionality. The important attributes of an ndarray object are:

` ndarray.ndim `:

The number of axes or dimensions of the array. It is referred to as rank.

` ndarray.shape `:

The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. The length of the shape tuple is therefore the rank, or number of dimensions, `ndim`.

` ndarray.size `:

The total number of elements of the array. This is the product of the elements of shape.

` ndarray.dtype `:

An object describing the type of the elements in the array. 

` ndarray.itemsize `:

The size in bytes of each element of the array. It is equivalent to ndarray.dtype.itemsize.

` ndarray.data `:

The buffer containing the actual elements of the array. we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [2]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
int64
8
12


numpy.ndarray

# Array Creation
An array can be created from a Python list or a tuple using `array()`. 

In [3]:
b = np.array([5,10,15])
b

array([ 5, 10, 15])

`array()` transforms sequences of sequences into two-dimensional arrays. sequences of sequences of sequences using  `array()` turns into three-dimensional arrays, and so on.

In [4]:
b = np.array([(.1,.2,.3), (1,2,3), (10, 20, 30)])
b

array([[  0.1,   0.2,   0.3],
       [  1. ,   2. ,   3. ],
       [ 10. ,  20. ,  30. ]])

The type of the array can also be explicitly specified at creation time:

In [5]:
c = np.array([1, 2, 3], dtype=complex)
c

array([ 1.+0.j,  2.+0.j,  3.+0.j])

The elements of an array might not be originally unknown, but its size is known. NumPy has several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays.

The ` zeros()` creates an array full of zeros, the `ones()` creates an array full of ones, and the `empty()` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is `float64`.

In [6]:
d = np.zeros( (3,5) )
d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
e = np.ones( (2,4,3), dtype=np.int16 ) 
e

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [8]:
f = np.empty([2,2])  
f

array([[  0.00000000e+000,   0.00000000e+000],
       [  2.14378692e-314,   2.78136376e-309]])

To create sequences of numbers in the form of numpy array, `arrange()` can be used. 

NumPy displays an array like a nested lists, but with the following layout:

- The last axis is printed from left to right,
- The second-to-last is printed from top to bottom,
- The rest are also printed from top to bottom, with each slice separated from the next by an empty line.

`arrange()` accepts float arguments:

In [9]:
g = np.arange( 1, 4, 0.2 )
g

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8])

One-dimensional arrays are printed as rows:

In [10]:
h = np.arange(24)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

bidimensional arrays are printed as matrices:

In [11]:
h.reshape(8,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

tridimensionals arrays are printed as lists of matrices:

In [12]:
h.reshape(2,3,4) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Basic Operations

Arithmetic operators on numpy arrays apply on each and every element of the array. A new array then filled with the results.

In [15]:
i = np.array([10, 9, 8, 7])
j = np.array([1, 2, 3, 4])
k = i - j
print(k)
print(j ** 3)
print(10 * j)
i * j

[9 7 5 3]
[ 1  8 27 64]
[10 20 30 40]


array([10, 18, 24, 28])

In the last example, the product operator `* `operated elementwis in NumPy arrays. The matrix product can be performed using the dot function or method:

In [18]:
print(i.dot(j)) 
np.dot(i, j)

80


80

Operations, such as `+=` and `*=` modify an existing array in place.

In [22]:
l = np.ones((2,3), dtype=int)
print(l)
l *= 5
print(l)
l += 2
print(l)

[[1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]]
[[7 7 7]
 [7 7 7]]


Operations, such as sum of all the elements in the array, are implemented as methods of the ndarray class.

In [25]:
n = np.random.random((3,3))
print(n)
print(n.sum())
print(n.min())
n.max()

[[ 0.87333271  0.57839983  0.36369939]
 [ 0.19977155  0.85852822  0.51949003]
 [ 0.47819023  0.66995526  0.99251729]]
5.533884513
0.199771551694


0.99251728797056948

By specifying the axis parameter, an operation along that specified axis of an array can be applied:

In [27]:
o = np.arange(25).reshape(5,5)
print(o)
print(o.sum(axis = 0))
o.cumsum(axis = 1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[50 55 60 65 70]


array([[  0,   1,   3,   6,  10],
       [  5,  11,  18,  26,  35],
       [ 10,  21,  33,  46,  60],
       [ 15,  31,  48,  66,  85],
       [ 20,  41,  63,  86, 110]])

# Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over like lists.

In [38]:
q = np.arange(8)
print(q)
print(q[3])
print(q[1:6])
q[:7:2] = -1
# equivalent to a[0:7:2] = -1; from start to position 7, exclusive, set every 2nd element to -1.
print(q)
q[: :-1]                           
# reversed q
print(q)
for i in q:
    print(i*2)

[0 1 2 3 4 5 6 7]
3
[1 2 3 4 5]
[-1  1 -1  3 -1  5 -1  7]
[-1  1 -1  3 -1  5 -1  7]
-2
2
-2
6
-2
10
-2
14


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [44]:
r = np.arange(25).reshape(5,5)
print(r)
print(r[2,3])
print(r[0:5, 1])
print(r[ : ,1])
r[1:3, :]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
13
[ 1  6 11 16 21]
[ 1  6 11 16 21]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Once fewer indices are provided than the number of axes, the missing indices are considered complete slices. The i in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].
The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].

In [48]:
print(r[-2])
s = np.array( [[[  1,  2,  3],             
                [ 10, 12, 13]],
               [[101,102,103],
                [110,112,113]]])
print(s.shape)
print(s[1,...])                     # same as c[1,:,:] or c[1]
s[...,2]                            # same as c[:,:,2]

[15 16 17 18 19]
(2, 2, 3)
[[101 102 103]
 [110 112 113]]


array([[  3,  13],
       [103, 113]])