The following tutorial has been adopted from [_**Quickstart tutorial**: Numpy User Guide_]
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

# NumPy Array
NumPy array is a homogeneous and multidimensional array. All of the elements are same type and indexed by a tuple of positive integers. 
NumPy’s array class is called ` ndarray `. The alias ` array ` refers to ` ndarray `. Note that ` numpy.array ` is not the same as the Standard Python Library class ` array.array `, which only handles one-dimensional arrays and offers less functionality. The important attributes of an ndarray object are:

` ndarray.ndim `:

The number of axes or dimensions of the array. It is referred to as rank.

` ndarray.shape `:

The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. The length of the shape tuple is therefore the rank, or number of dimensions, `ndim`.

` ndarray.size `:

The total number of elements of the array. This is the product of the elements of shape.

` ndarray.dtype `:

An object describing the type of the elements in the array. 

` ndarray.itemsize `:

The size in bytes of each element of the array. It is equivalent to ndarray.dtype.itemsize.

` ndarray.data `:

The buffer containing the actual elements of the array. we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [2]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
int64
8
12


numpy.ndarray

# Array Creation
An array can be created from a Python list or a tuple using `array()`. 

In [7]:
b = np.array([5,10,15])
b

array([ 5, 10, 15])

`array()` transforms sequences of sequences into two-dimensional arrays. sequences of sequences of sequences using  `array()` turns into three-dimensional arrays, and so on.

In [9]:
b = np.array([(.1,.2,.3), (1,2,3), (10, 20, 30)])
b

array([[  0.1,   0.2,   0.3],
       [  1. ,   2. ,   3. ],
       [ 10. ,  20. ,  30. ]])

The type of the array can also be explicitly specified at creation time:

In [10]:
c = np.array([1, 2, 3], dtype=complex)
c

array([ 1.+0.j,  2.+0.j,  3.+0.j])

The elements of an array might not be originally unknown, but its size is known. NumPy has several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays.

The ` zeros()` creates an array full of zeros, the `ones()` creates an array full of ones, and the `empty()` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is `float64`.

In [12]:
d = np.zeros( (3,5) )
d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
e = np.ones( (2,4,3), dtype=np.int16 ) 
e

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [19]:
f = np.empty([2,2])  
f

array([[  0.00000000e+000,   0.00000000e+000],
       [  2.15919936e-314,   2.78134232e-309]])

To create sequences of numbers in the form of numpy array, `arrange()` can be used. 

NumPy displays an array like a nested lists, but with the following layout:

- The last axis is printed from left to right,
- The second-to-last is printed from top to bottom,
- The rest are also printed from top to bottom, with each slice separated from the next by an empty line.

`arrange()` accepts float arguments:

In [21]:
g = np.arange( 1, 4, 0.2 )
g

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8])

One-dimensional arrays are printed as rows:

In [23]:
h = np.arange(24)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

bidimensional arrays are printed as matrices:

In [24]:
h.reshape(8,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

tridimensionals arrays are printed as lists of matrices:

In [25]:
h.reshape(2,3,4) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Basic Operations

Arithmetic operators on numpy arrays apply on each and every element of the array. A new array then filled with the results.

In [ ]:
i = np.array